# 公共配置文件
server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yupi
      routes:
        # 平台业务接口路由 - 需要登录认证
        - id: platform_api_route
          uri: http://localhost:8101
          predicates:
            - Path=/api/**
        # 用户相关接口 - 支持登录注册等
        - id: user_route
          uri: http://localhost:8101
          predicates:
            - Path=/user/**
        # 接口信息管理 - 包含invoke调试
        - id: interface_route
          uri: http://localhost:8101
          predicates:
            - Path=/interfaceInfo/**
        # 数据分析接口
        - id: analysis_route
          uri: http://localhost:8101
          predicates:
            - Path=/analysis/**
        # 第三方API调用路由 - 需要密钥认证
        - id: third_party_api_route
          uri: http://localhost:8101
          predicates:
            - Path=/third-party/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848