# 生产环境配置文件
server:
  port: 8077
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, qiapi
      routes:
        # 平台业务接口路由 - 需要登录认证
        - id: platform_api_route
          uri: http://localhost:8101
          predicates:
            - Path=/api/**
        # 用户相关接口 - 支持登录注册等
        - id: user_route
          uri: http://localhost:8101
          predicates:
            - Path=/user/**
        # 接口信息管理 - 包含invoke调试
        - id: interface_route
          uri: http://localhost:8101
          predicates:
            - Path=/interfaceInfo/**
        # 数据分析接口
        - id: analysis_route
          uri: http://localhost:8101
          predicates:
            - Path=/analysis/**
        # 第三方API调用路由 - 需要密钥认证
        - id: third_party_api_route
          uri: http://localhost:8101
          predicates:
            - Path=/third-party/**

# Dubbo 配置
dubbo:
  application:
    name: qiapi-gateway
    # 关闭Dubbo的QoS端口，避免端口冲突
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
    timeout: 60000
    # 优化连接参数
    parameters:
      registry.check: false
      subscribe.only: false
      # 设置重试次数和间隔
      retry.times: 3
      retry.period: 5000
      # 设置心跳间隔
      heartbeat: 60000
  # 消费者配置
  consumer:
    # 关闭启动时检查
    check: false
    timeout: 60000
    retries: 2

# 日志配置
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: INFO